# Instalacion de base de datos MongoDB en mi equipo mediante docker:


version: '3'

services:
  db:
    container_name: mean-db
    image: mongo:5.0.16
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    restart: always
